manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: george-norton
      url-base: https://github.com/george-norton
  projects:
    - name: zmk
      remote: george-norton
      revision: behaviors/mouse-key-press-metadata
      import: app/west.yml
    - name: zmk-driver-pmw3360
      remote: george-norton
      revision: main
    - name: zmk-behavior-sensor-attr-cycle
      remote: george-norton
      revision: main